// SPDX-License-Identifier: MPL-2.0
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.
//
// Copyright (c) DUSK NETWORK. All rights reserved.

// This file is generated by dusk-groth16. Do not edit it manually.
// It requires the EIP-2537 BLS12-381 precompiles introduced by Pectra.
pragma solidity ^0.8.30;

contract SquareVerifier {
    uint256 internal constant SCALAR_MODULUS = 0x73eda753299d7d483339d80809a1d80553bda402fffe5bfeffffffff00000001;
    uint256 internal constant PUBLIC_INPUTS = 1;

    /// Verify a Groth16 proof converted with `Proof::to_eip2537`.
    /// @param proof 512-byte EIP-2537 transport encoding of (-A, B, C).
    /// @param publicInputs Scalars in Composer emission order.
    function verifyProof(bytes calldata proof, uint256[] calldata publicInputs) external view returns (bool) {
        if (proof.length != 512 || publicInputs.length != PUBLIC_INPUTS) {
            return false;
        }
        for (uint256 i = 0; i < PUBLIC_INPUTS; ++i) {
            if (publicInputs[i] >= SCALAR_MODULUS) {
                return false;
            }
        }

        assembly ("memory-safe") {
            function fail() {
                mstore(0, 0)
                return(0, 0x20)
            }

            function calldataG1IsInfinity(point) -> result {
                result := iszero(
                    or(
                        or(calldataload(point), calldataload(add(point, 0x20))),
                        or(calldataload(add(point, 0x40)), calldataload(add(point, 0x60)))
                    )
                )
            }

            function calldataG2IsInfinity(point) -> result {
                result := iszero(
                    or(
                        or(
                            or(calldataload(point), calldataload(add(point, 0x20))),
                            or(calldataload(add(point, 0x40)), calldataload(add(point, 0x60)))
                        ),
                        or(
                            or(calldataload(add(point, 0x80)), calldataload(add(point, 0xa0))),
                            or(calldataload(add(point, 0xc0)), calldataload(add(point, 0xe0)))
                        )
                    )
                )
            }

            function storeG1(point, xHi, xLo, yHi, yLo) {
                mstore(point, xHi)
                mstore(add(point, 0x20), xLo)
                mstore(add(point, 0x40), yHi)
                mstore(add(point, 0x60), yLo)
            }

            function storeG2(point, x0Hi, x0Lo, x1Hi, x1Lo, y0Hi, y0Lo, y1Hi, y1Lo) {
                mstore(point, x0Hi)
                mstore(add(point, 0x20), x0Lo)
                mstore(add(point, 0x40), x1Hi)
                mstore(add(point, 0x60), x1Lo)
                mstore(add(point, 0x80), y0Hi)
                mstore(add(point, 0xa0), y0Lo)
                mstore(add(point, 0xc0), y1Hi)
                mstore(add(point, 0xe0), y1Lo)
            }

            let proofOffset := proof.offset
            if calldataG1IsInfinity(proofOffset) { fail() }
            if calldataG2IsInfinity(add(proofOffset, 0x80)) { fail() }
            if calldataG1IsInfinity(add(proofOffset, 0x180)) { fail() }

            let msmInput := mload(0x40)
            storeG1(
                add(msmInput, 0x0),
                0x000000000000000000000000000000000ea8a2186c30948ae9908d8abdb96146,
                0xcf5e32dcc56aead0cc2d3bfd36c0748593410747ddbd18d4e20ea7469df6fee1,
                0x000000000000000000000000000000000525503a8591d0ac7993054d9dbd603b,
                0x77c94948435a82383be7c89ef2c47ade70f2d413b1e2b121804c5e4e3f685b55
            )
            mstore(add(msmInput, 0x80), 1)
            storeG1(
                add(msmInput, 0xa0),
                0x0000000000000000000000000000000017130d79dedb932cd2244e050f1ef86c,
                0x43c5e8de2b986c89a48b0a0e21c2b14b21aebae5987b7e34e2254ffaf910519f,
                0x0000000000000000000000000000000005aa983ffe98642459acdb2220d7f0ea,
                0x50dca94fc64305cedb262a2600fb06b2d47be488e8284dec54e9f101ac8509b1
            )
            mstore(add(msmInput, 0x120), calldataload(add(publicInputs.offset, 0x0)))

            let vkX := add(msmInput, 0x140)
            let pairingInput := add(vkX, 0x80)
            let pairingResult := add(pairingInput, 0x600)
            mstore(0x40, add(pairingResult, 0x20))

            // IC[0] + sum(publicInputs[i] * IC[i + 1]).
            // Invalid EIP-2537 input burns all forwarded gas, so cap the call.
            let success := staticcall(24000, 0x0c, msmInput, 0x140, vkX, 0x80)
            if iszero(and(success, eq(returndatasize(), 0x80))) { fail() }

            // Pair 0: (-A, B), copied from the proof transport encoding.
            calldatacopy(pairingInput, proofOffset, 0x180)

            storeG1(
                add(pairingInput, 0x180),
                0x0000000000000000000000000000000017f5804f26e6366dc96f3020bb7bc3ea,
                0x1c4c741557b89ff74a858530f49413fd8428f3b2c9f4f78cd53bc3a88b11d100,
                0x00000000000000000000000000000000056c97c03163f96c1e33026a92a21e9e,
                0xe0af11d8471e0d795d0e71012b40812225d720cae21baf0388b274531be367f6
            )
            storeG2(
                add(pairingInput, 0x200),
                0x0000000000000000000000000000000013c0531bb82d5b68115ab5b2620838de,
                0x3776daa44a4564a476816597ce7e077f0601b8b947dfdfc9c3891d5516ed0f21,
                0x00000000000000000000000000000000008a25574a1018104568150fe7d57dc6,
                0x367ecee2ea6d29b142dd8cc85cc77ea795816d3de139ed7681acf3566bfba8c9,
                0x000000000000000000000000000000001779dfe08ec1cc4bb96ba1c787a6fd30,
                0x7d13271522dda81dc14ce77c11f25d74344901f36c7215f9bbf41d668389ca09,
                0x000000000000000000000000000000001497cb8e081b5aacf52a1c96e40ef8b7,
                0xe52a9f9315a1411e1f9fe70f5fd95434a3e2c9496b2e5fd1ec29fa9cb3d259a1
            )

            // Pair 2: (vkX, gamma).
            mstore(add(pairingInput, 0x300), mload(vkX))
            mstore(add(pairingInput, 0x320), mload(add(vkX, 0x20)))
            mstore(add(pairingInput, 0x340), mload(add(vkX, 0x40)))
            mstore(add(pairingInput, 0x360), mload(add(vkX, 0x60)))
            storeG2(
                add(pairingInput, 0x380),
                0x00000000000000000000000000000000034dabde4d7945db55270f657ddbbc95,
                0xb587b928fb5095fe050cad499f4432d080ba73d2506275e448c7802ddf4629a0,
                0x0000000000000000000000000000000003a45f0edfb82df44c66e9cc758a1726,
                0x0d74631cd7cf4cc04bb21138c747f09aa7d881b66636e868b25bb5cc6dff3159,
                0x00000000000000000000000000000000007046fcb1053c92a5292b3ec748a970,
                0xc09e0ddb1f0c550a31ef6f1a3d5afe446a771be6989923b1be3fb36d98456288,
                0x000000000000000000000000000000000dfc855563522b8bd6d85428843a6e8b,
                0x23e8dcaab99f1cb274e0c1885146db67ee7fddd70534deea27a104deaa3c3b77
            )

            // Pair 3: (C, delta).
            calldatacopy(add(pairingInput, 0x480), add(proofOffset, 0x180), 0x80)
            storeG2(
                add(pairingInput, 0x500),
                0x000000000000000000000000000000000859f6b7bc0a835081afd02871e00a1e,
                0xcaaca13d92a4b4c44dba626e22fddc12d314ad566d6f845747554830225acfde,
                0x0000000000000000000000000000000007df93d579f13b452c72647bbf33cf70,
                0x82199c5dc5a2ba6dd8a31a12f43718ba000a024f4982c008442c3e725917f468,
                0x000000000000000000000000000000001163ea475915912fcbfba4f5449cb010,
                0xa9fbdf0b1846b46d63103a7e64291c204aebb131c206de66833715a2b199202c,
                0x000000000000000000000000000000000024abf52bca99f29a410c4c9692068c,
                0xc9eacd502cfe78c8e8fdf02aa3d58e8ffd87c49ea3a33310dcbf732241388806
            )

            mstore(pairingResult, 0)
            // Four pairs cost 4 * 32600 + 37700 gas under EIP-2537.
            success := staticcall(168100, 0x0f, pairingInput, 0x600, pairingResult, 0x20)
            let valid := and(and(success, eq(returndatasize(), 0x20)), eq(mload(pairingResult), 1))
            mstore(0, valid)
            return(0, 0x20)
        }
    }
}
