// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.
//
// Copyright (c) DUSK NETWORK. All rights reserved.

//! EIP-2537 proof encoding and circuit-specific Solidity verifier generation.

use alloc::string::String;
use core::{fmt, fmt::Write};

use dusk_curves::bls12_381::{BlsScalar, G1Affine, G2Affine};

use crate::{Proof, VerifyingKey};

/// Size of a Groth16 proof encoded for the EIP-2537 pairing precompile.
///
/// The encoding contains a 128-byte G1 point, a 256-byte G2 point, and a
/// second 128-byte G1 point. Unlike the crate's canonical proof encoding, points
/// are uncompressed and every base-field element is left-padded to 64 bytes.
pub const EIP2537_PROOF_SIZE: usize = 512;

const EIP2537_G1_SIZE: usize = 128;
const EIP2537_G2_SIZE: usize = 256;

/// Encode a BLS scalar as the big-endian 32-byte word expected by the EVM.
///
/// The crate's canonical scalar encoding is little-endian. This helper is useful
/// when constructing ABI calldata without a library that already accepts
/// arbitrary-precision integers.
pub fn encode_eip2537_scalar(scalar: &BlsScalar) -> [u8; 32] {
    let mut encoded = scalar.to_bytes();
    encoded.reverse();
    encoded
}

/// A Groth16 proof prepared for the EIP-2537 pairing check.
///
/// Its byte layout is `(-A, B, C)`, where `-A` and `C` use the EIP-2537 G1
/// encoding and `B` uses the EIP-2537 G2 encoding. Negating `A` during export
/// avoids implementing 381-bit base-field negation in Solidity. This is a
/// transport representation; [`Proof::to_bytes`](dusk_bytes::Serializable::to_bytes)
/// remains the crate's canonical proof encoding.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Eip2537Proof([u8; EIP2537_PROOF_SIZE]);

impl Eip2537Proof {
    /// Borrow the encoded proof.
    pub const fn as_bytes(&self) -> &[u8; EIP2537_PROOF_SIZE] {
        &self.0
    }

    /// Consume the wrapper and return the encoded proof.
    pub const fn into_bytes(self) -> [u8; EIP2537_PROOF_SIZE] {
        self.0
    }
}

impl AsRef<[u8]> for Eip2537Proof {
    fn as_ref(&self) -> &[u8] {
        &self.0
    }
}

/// Errors returned while generating a Solidity verifier.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[non_exhaustive]
pub enum SolidityError {
    /// The requested contract name is not a Solidity identifier.
    InvalidContractName,
    /// Formatting the generated source failed.
    Formatting,
}

impl fmt::Display for SolidityError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidContractName => formatter.write_str("invalid Solidity contract name"),
            Self::Formatting => formatter.write_str("failed to format Solidity verifier"),
        }
    }
}

#[cfg(feature = "std")]
impl std::error::Error for SolidityError {}

impl Proof {
    /// Encode this proof for a generated EIP-2537 Solidity verifier.
    ///
    /// The generated verifier expects this exact `(-A, B, C)` transport
    /// encoding rather than the canonical 192-byte compressed proof.
    pub fn to_eip2537(&self) -> Eip2537Proof {
        let mut bytes = [0u8; EIP2537_PROOF_SIZE];
        bytes[..EIP2537_G1_SIZE].copy_from_slice(&encode_g1(&(-self.a)));
        bytes[EIP2537_G1_SIZE..EIP2537_G1_SIZE + EIP2537_G2_SIZE]
            .copy_from_slice(&encode_g2(&self.b));
        bytes[EIP2537_G1_SIZE + EIP2537_G2_SIZE..].copy_from_slice(&encode_g1(&self.c));
        Eip2537Proof(bytes)
    }
}

impl VerifyingKey {
    /// Generate a circuit-specific Solidity verifier backed by EIP-2537.
    ///
    /// The verification key and expected public-input count are embedded in
    /// the returned source. Generate a new contract whenever setup produces a
    /// different verification key. The target EVM must implement EIP-2537.
    pub fn solidity_verifier(&self, contract_name: &str) -> Result<String, SolidityError> {
        if !valid_contract_name(contract_name) {
            return Err(SolidityError::InvalidContractName);
        }

        let mut source = String::new();
        write!(
            source,
            r#"// SPDX-License-Identifier: MPL-2.0
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.
//
// Copyright (c) DUSK NETWORK. All rights reserved.

// This file is generated by dusk-groth16. Do not edit it manually.
// It requires the EIP-2537 BLS12-381 precompiles introduced by Pectra.
pragma solidity ^0.8.30;

contract {contract_name} {{
    uint256 internal constant SCALAR_MODULUS = 0x73eda753299d7d483339d80809a1d80553bda402fffe5bfeffffffff00000001;
    uint256 internal constant PUBLIC_INPUTS = {public_inputs};

    /// Verify a Groth16 proof converted with `Proof::to_eip2537`.
    /// @param proof 512-byte EIP-2537 transport encoding of (-A, B, C).
    /// @param publicInputs Scalars in Composer emission order.
    function verifyProof(bytes calldata proof, uint256[] calldata publicInputs) external view returns (bool) {{
        if (proof.length != 512 || publicInputs.length != PUBLIC_INPUTS) {{
            return false;
        }}
        for (uint256 i = 0; i < PUBLIC_INPUTS; ++i) {{
            if (publicInputs[i] >= SCALAR_MODULUS) {{
                return false;
            }}
        }}

        assembly ("memory-safe") {{
            function fail() {{
                mstore(0, 0)
                return(0, 0x20)
            }}

            function calldataG1IsInfinity(point) -> result {{
                result := iszero(
                    or(
                        or(calldataload(point), calldataload(add(point, 0x20))),
                        or(calldataload(add(point, 0x40)), calldataload(add(point, 0x60)))
                    )
                )
            }}

            function calldataG2IsInfinity(point) -> result {{
                result := iszero(
                    or(
                        or(
                            or(calldataload(point), calldataload(add(point, 0x20))),
                            or(calldataload(add(point, 0x40)), calldataload(add(point, 0x60)))
                        ),
                        or(
                            or(calldataload(add(point, 0x80)), calldataload(add(point, 0xa0))),
                            or(calldataload(add(point, 0xc0)), calldataload(add(point, 0xe0)))
                        )
                    )
                )
            }}

            function storeG1(point, xHi, xLo, yHi, yLo) {{
                mstore(point, xHi)
                mstore(add(point, 0x20), xLo)
                mstore(add(point, 0x40), yHi)
                mstore(add(point, 0x60), yLo)
            }}

            function storeG2(point, x0Hi, x0Lo, x1Hi, x1Lo, y0Hi, y0Lo, y1Hi, y1Lo) {{
                mstore(point, x0Hi)
                mstore(add(point, 0x20), x0Lo)
                mstore(add(point, 0x40), x1Hi)
                mstore(add(point, 0x60), x1Lo)
                mstore(add(point, 0x80), y0Hi)
                mstore(add(point, 0xa0), y0Lo)
                mstore(add(point, 0xc0), y1Hi)
                mstore(add(point, 0xe0), y1Lo)
            }}

            let proofOffset := proof.offset
            if calldataG1IsInfinity(proofOffset) {{ fail() }}
            if calldataG2IsInfinity(add(proofOffset, 0x80)) {{ fail() }}
            if calldataG1IsInfinity(add(proofOffset, 0x180)) {{ fail() }}

            let msmInput := mload(0x40)
"#,
            public_inputs = self.public_inputs()
        )
        .map_err(|_| SolidityError::Formatting)?;

        for (index, point) in self.public_query.iter().enumerate() {
            let offset = index * 160;
            write_store_g1(&mut source, "msmInput", offset, point)?;
            if index == 0 {
                writeln!(
                    source,
                    "            mstore(add(msmInput, 0x{:x}), 1)",
                    offset + 128
                )
                .map_err(|_| SolidityError::Formatting)?;
            } else {
                writeln!(
                    source,
                    "            mstore(add(msmInput, 0x{:x}), calldataload(add(publicInputs.offset, 0x{:x})))",
                    offset + 128,
                    (index - 1) * 32
                )
                .map_err(|_| SolidityError::Formatting)?;
            }
        }

        let msm_size = self.public_query.len() * 160;
        // The EIP discount makes the actual MSM charge no greater than one
        // G1 multiplication per term. Capping forwarded gas prevents malformed
        // points from burning nearly all gas available to the verifier.
        let msm_gas = self.public_query.len() * 12_000;
        writeln!(
            source,
            r#"
            let vkX := add(msmInput, 0x{msm_size:x})
            let pairingInput := add(vkX, 0x80)
            let pairingResult := add(pairingInput, 0x600)
            mstore(0x40, add(pairingResult, 0x20))

            // IC[0] + sum(publicInputs[i] * IC[i + 1]).
            // Invalid EIP-2537 input burns all forwarded gas, so cap the call.
            let success := staticcall({msm_gas}, 0x0c, msmInput, 0x{msm_size:x}, vkX, 0x80)
            if iszero(and(success, eq(returndatasize(), 0x80))) {{ fail() }}

            // Pair 0: (-A, B), copied from the proof transport encoding.
            calldatacopy(pairingInput, proofOffset, 0x180)
"#
        )
        .map_err(|_| SolidityError::Formatting)?;

        write_store_g1(&mut source, "pairingInput", 0x180, &self.alpha_g1)?;
        write_store_g2(&mut source, "pairingInput", 0x200, &self.beta_g2)?;

        source.push_str(
            r#"
            // Pair 2: (vkX, gamma).
            mstore(add(pairingInput, 0x300), mload(vkX))
            mstore(add(pairingInput, 0x320), mload(add(vkX, 0x20)))
            mstore(add(pairingInput, 0x340), mload(add(vkX, 0x40)))
            mstore(add(pairingInput, 0x360), mload(add(vkX, 0x60)))
"#,
        );
        write_store_g2(&mut source, "pairingInput", 0x380, &self.gamma_g2)?;

        source.push_str(
            r#"
            // Pair 3: (C, delta).
            calldatacopy(add(pairingInput, 0x480), add(proofOffset, 0x180), 0x80)
"#,
        );
        write_store_g2(&mut source, "pairingInput", 0x500, &self.delta_g2)?;

        source.push_str(
            r#"
            mstore(pairingResult, 0)
            // Four pairs cost 4 * 32600 + 37700 gas under EIP-2537.
            success := staticcall(168100, 0x0f, pairingInput, 0x600, pairingResult, 0x20)
            let valid := and(and(success, eq(returndatasize(), 0x20)), eq(mload(pairingResult), 1))
            mstore(0, valid)
            return(0, 0x20)
        }
    }
}
"#,
        );

        Ok(source)
    }
}

fn valid_contract_name(name: &str) -> bool {
    let mut bytes = name.bytes();
    let Some(first) = bytes.next() else {
        return false;
    };
    (first == b'_' || first.is_ascii_alphabetic())
        && bytes.all(|byte| byte == b'_' || byte.is_ascii_alphanumeric())
        && !solidity_reserved_name(name)
}

fn solidity_reserved_name(name: &str) -> bool {
    if matches!(
        name,
        "abstract"
            | "after"
            | "alias"
            | "anonymous"
            | "apply"
            | "as"
            | "assembly"
            | "auto"
            | "break"
            | "byte"
            | "calldata"
            | "case"
            | "catch"
            | "constant"
            | "constructor"
            | "continue"
            | "contract"
            | "copyof"
            | "default"
            | "define"
            | "delete"
            | "do"
            | "else"
            | "emit"
            | "enum"
            | "error"
            | "event"
            | "external"
            | "fallback"
            | "false"
            | "final"
            | "for"
            | "from"
            | "function"
            | "global"
            | "if"
            | "immutable"
            | "implements"
            | "import"
            | "in"
            | "indexed"
            | "inline"
            | "interface"
            | "internal"
            | "is"
            | "leave"
            | "let"
            | "library"
            | "macro"
            | "mapping"
            | "match"
            | "memory"
            | "modifier"
            | "mutable"
            | "new"
            | "null"
            | "of"
            | "override"
            | "partial"
            | "payable"
            | "pragma"
            | "private"
            | "promise"
            | "public"
            | "pure"
            | "receive"
            | "reference"
            | "relocatable"
            | "return"
            | "returns"
            | "revert"
            | "sealed"
            | "sizeof"
            | "static"
            | "storage"
            | "string"
            | "struct"
            | "supports"
            | "switch"
            | "this"
            | "throw"
            | "transient"
            | "true"
            | "try"
            | "type"
            | "typedef"
            | "typeof"
            | "unchecked"
            | "using"
            | "var"
            | "view"
            | "virtual"
            | "while"
    ) {
        return true;
    }

    matches!(
        name,
        "address" | "bool" | "bytes" | "fixed" | "int" | "ufixed" | "uint"
    ) || solidity_integer_type(name, "int")
        || solidity_integer_type(name, "uint")
        || name
            .strip_prefix("bytes")
            .and_then(|width| width.parse::<u8>().ok())
            .is_some_and(|width| (1..=32).contains(&width))
        || solidity_fixed_type(name, "fixed")
        || solidity_fixed_type(name, "ufixed")
}

fn solidity_integer_type(name: &str, prefix: &str) -> bool {
    name.strip_prefix(prefix)
        .and_then(|width| width.parse::<u16>().ok())
        .is_some_and(|width| (8..=256).contains(&width) && width % 8 == 0)
}

fn solidity_fixed_type(name: &str, prefix: &str) -> bool {
    name.strip_prefix(prefix)
        .and_then(|dimensions| dimensions.split_once('x'))
        .and_then(|(width, decimals)| {
            Some((width.parse::<u16>().ok()?, decimals.parse::<u8>().ok()?))
        })
        .is_some_and(|(width, decimals)| {
            (8..=256).contains(&width) && width % 8 == 0 && decimals <= 80
        })
}

fn encode_g1(point: &G1Affine) -> [u8; EIP2537_G1_SIZE] {
    if bool::from(point.is_identity()) {
        return [0u8; EIP2537_G1_SIZE];
    }

    let uncompressed = point.to_uncompressed();
    let mut encoded = [0u8; EIP2537_G1_SIZE];
    encoded[16..64].copy_from_slice(&uncompressed[..48]);
    encoded[80..128].copy_from_slice(&uncompressed[48..]);
    encoded
}

fn encode_g2(point: &G2Affine) -> [u8; EIP2537_G2_SIZE] {
    if bool::from(point.is_identity()) {
        return [0u8; EIP2537_G2_SIZE];
    }

    // dusk-curves follows the IETF serialization order c1 || c0, whereas
    // EIP-2537 requires c0 || c1 for every Fp2 element.
    let uncompressed = point.to_uncompressed();
    let mut encoded = [0u8; EIP2537_G2_SIZE];
    encoded[16..64].copy_from_slice(&uncompressed[48..96]);
    encoded[80..128].copy_from_slice(&uncompressed[..48]);
    encoded[144..192].copy_from_slice(&uncompressed[144..192]);
    encoded[208..256].copy_from_slice(&uncompressed[96..144]);
    encoded
}

fn write_store_g1(
    source: &mut String,
    base: &str,
    offset: usize,
    point: &G1Affine,
) -> Result<(), SolidityError> {
    let encoded = encode_g1(point);
    writeln!(
        source,
        "            storeG1(\n                add({base}, 0x{offset:x}),\n                0x{},\n                0x{},\n                0x{},\n                0x{}\n            )",
        HexWord(&encoded[0..32]),
        HexWord(&encoded[32..64]),
        HexWord(&encoded[64..96]),
        HexWord(&encoded[96..128]),
    )
    .map_err(|_| SolidityError::Formatting)
}

fn write_store_g2(
    source: &mut String,
    base: &str,
    offset: usize,
    point: &G2Affine,
) -> Result<(), SolidityError> {
    let encoded = encode_g2(point);
    write!(
        source,
        "            storeG2(\n                add({base}, 0x{offset:x})"
    )
    .map_err(|_| SolidityError::Formatting)?;
    for word in encoded.chunks_exact(32) {
        write!(source, ",\n                0x{}", HexWord(word))
            .map_err(|_| SolidityError::Formatting)?;
    }
    source.push_str("\n            )\n");
    Ok(())
}

struct HexWord<'a>(&'a [u8]);

impl fmt::Display for HexWord<'_> {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        for byte in self.0 {
            write!(formatter, "{byte:02x}")?;
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use dusk_curves::bls12_381::BlsScalar;

    fn decode_hex<const N: usize>(value: &str) -> [u8; N] {
        assert_eq!(value.len(), N * 2);
        let mut output = [0u8; N];
        for (index, byte) in output.iter_mut().enumerate() {
            *byte = u8::from_str_radix(&value[index * 2..index * 2 + 2], 16).unwrap();
        }
        output
    }

    #[test]
    fn eip2537_generator_encodings_match_the_specification() {
        let g1 = encode_g1(&G1Affine::generator());
        assert_eq!(&g1[..16], &[0u8; 16]);
        assert_eq!(
            &g1[16..64],
            &decode_hex::<48>(
                "17f1d3a73197d7942695638c4fa9ac0fc3688c4f9774b905a14e3a3f171bac586c55e83ff97a1aeffb3af00adb22c6bb"
            )
        );
        assert_eq!(
            &g1[80..128],
            &decode_hex::<48>(
                "08b3f481e3aaa0f1a09e30ed741d8ae4fcf5e095d5d00af600db18cb2c04b3edd03cc744a2888ae40caa232946c5e7e1"
            )
        );

        let g2 = encode_g2(&G2Affine::generator());
        for offset in [0, 64, 128, 192] {
            assert_eq!(&g2[offset..offset + 16], &[0u8; 16]);
        }
        for (offset, expected) in [
            (
                16,
                "024aa2b2f08f0a91260805272dc51051c6e47ad4fa403b02b4510b647ae3d1770bac0326a805bbefd48056c8c121bdb8",
            ),
            (
                80,
                "13e02b6052719f607dacd3a088274f65596bd0d09920b61ab5da61bbdc7f5049334cf11213945d57e5ac7d055d042b7e",
            ),
            (
                144,
                "0ce5d527727d6e118cc9cdc6da2e351aadfd9baa8cbdd3a76d429a695160d12c923ac9cc3baca289e193548608b82801",
            ),
            (
                208,
                "0606c4a02ea734cc32acd2b02bc28b99cb3e287e85a763af267492ab572e99ab3f370d275cec1da1aaa9075ff05f79be",
            ),
        ] {
            assert_eq!(&g2[offset..offset + 48], &decode_hex::<48>(expected));
        }
    }

    #[test]
    fn proof_transport_is_neg_a_b_c() {
        let proof = Proof {
            a: G1Affine::generator(),
            b: G2Affine::generator(),
            c: G1Affine::from(G1Affine::generator() * BlsScalar::from(2u64)),
        };
        let encoded = proof.to_eip2537().into_bytes();
        assert_eq!(&encoded[..128], &encode_g1(&(-proof.a)));
        assert_eq!(&encoded[128..384], &encode_g2(&proof.b));
        assert_eq!(&encoded[384..], &encode_g1(&proof.c));
    }

    #[test]
    fn scalar_transport_is_big_endian() {
        let encoded = encode_eip2537_scalar(&BlsScalar::from(0x0102u64));
        assert_eq!(&encoded[..30], &[0u8; 30]);
        assert_eq!(&encoded[30..], &[1, 2]);
    }

    #[test]
    fn generated_verifier_is_key_specific_and_names_are_checked() {
        let key = VerifyingKey {
            alpha_g1: G1Affine::generator(),
            beta_g2: G2Affine::generator(),
            gamma_g2: G2Affine::generator(),
            delta_g2: G2Affine::generator(),
            public_query: alloc::vec![G1Affine::generator(), G1Affine::generator()],
        };
        let source = key.solidity_verifier("SquareVerifier").unwrap();
        assert!(source.contains("contract SquareVerifier"));
        assert!(source.contains("PUBLIC_INPUTS = 1"));
        assert!(source.contains("staticcall(24000, 0x0c"));
        assert!(source.contains("staticcall(168100, 0x0f"));
        assert_eq!(
            key.solidity_verifier("not-valid"),
            Err(SolidityError::InvalidContractName)
        );
        for invalid in ["", "1Verifier", "contract", "uint256", "bytes32"] {
            assert_eq!(
                key.solidity_verifier(invalid),
                Err(SolidityError::InvalidContractName)
            );
        }
    }

    #[test]
    fn generated_verifier_supports_different_public_input_counts() {
        let key = |public_inputs: usize| VerifyingKey {
            alpha_g1: G1Affine::generator(),
            beta_g2: G2Affine::generator(),
            gamma_g2: G2Affine::generator(),
            delta_g2: G2Affine::generator(),
            public_query: alloc::vec![G1Affine::generator(); public_inputs + 1],
        };

        let no_inputs = key(0).solidity_verifier("NoInputVerifier").unwrap();
        assert!(no_inputs.contains("PUBLIC_INPUTS = 0"));
        assert!(no_inputs.contains("msmInput, 0xa0, vkX"));
        assert!(!no_inputs.contains("publicInputs.offset"));

        let two_inputs = key(2).solidity_verifier("TwoInputVerifier").unwrap();
        assert!(two_inputs.contains("PUBLIC_INPUTS = 2"));
        assert!(two_inputs.contains("msmInput, 0x1e0, vkX"));
        assert!(two_inputs.contains("publicInputs.offset, 0x0"));
        assert!(two_inputs.contains("publicInputs.offset, 0x20"));
    }
}
